# Generated by Django 3.1.4 on 2021-10-08 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=12)),
                ('Gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=30)),
                ('day', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=30)),
                ('pattern', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='S_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=12)),
                ('Gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bankapp.s_details')),
                ('date', models.DateField(max_length=50)),
                ('day', models.CharField(max_length=30)),
                ('intime', models.TimeField(max_length=30)),
                ('outtime', models.TimeField(max_length=30)),
                ('hours', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='C_Documents',
            fields=[
                ('cust', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bankapp.c_details')),
                ('aadhar', models.CharField(max_length=50)),
                ('pan', models.CharField(max_length=30)),
                ('voting_card', models.CharField(max_length=30)),
                ('driving_license', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='S_Documents',
            fields=[
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bankapp.s_details')),
                ('aadhar', models.CharField(max_length=50)),
                ('pan', models.CharField(max_length=30)),
                ('voting_card', models.CharField(max_length=30)),
                ('driving_license', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=70)),
                ('start_date', models.DateField(max_length=30)),
                ('end_date', models.DateField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('sta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.s_details')),
            ],
        ),
    ]
