# Generated by Django 3.1.4 on 2021-10-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passbooks1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=30)),
                ('details', models.CharField(max_length=100)),
                ('cheque_no', models.CharField(max_length=50)),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('c_a_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.c_details')),
            ],
        ),
        migrations.CreateModel(
            name='Acct1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
                ('investments', models.IntegerField()),
                ('c_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.c_details')),
            ],
        ),
    ]
